CREATE DATABASE IF NOT EXISTS studentdb CHARACTER SET utf8mb4;
USE studentdb;

CREATE TABLE IF NOT EXISTS students (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(150) NOT NULL,
  course     VARCHAR(150) NOT NULL,
  year       ENUM('1st Year','2nd Year','3rd Year','4th Year') NOT NULL DEFAULT '1st Year',
  status     ENUM('Active','Leave','Graduated') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
